import { Channel, Stream, Category } from '@/types';

export const mockChannels: Channel[] = [
  {
    id: 1,
    name: 'InAdventure',
    username: 'inadventure',
    avatar: 'https://i.pravatar.cc/150?img=1',
    banner: 'https://picsum.photos/800/200?random=1',
    followers: 15200,
    isLive: true,
    isFollowing: true,
  },
  {
    id: 2,
    name: 'Circlemart',
    username: 'circlemart',
    avatar: 'https://i.pravatar.cc/150?img=2',
    banner: 'https://picsum.photos/800/200?random=2',
    followers: 8400,
    isLive: false,
    isFollowing: true,
  },
  {
    id: 3,
    name: 'Ironargyr',
    username: 'ironargyr',
    avatar: 'https://i.pravatar.cc/150?img=3',
    banner: 'https://picsum.photos/800/200?random=3',
    followers: 12500,
    isLive: true,
    isFollowing: true,
  },
  {
    id: 4,
    name: 'Kanagav',
    username: 'kanagav',
    avatar: 'https://i.pravatar.cc/150?img=4',
    banner: 'https://picsum.photos/800/200?random=4',
    followers: 6700,
    isLive: false,
    isFollowing: true,
  },
  {
    id: 5,
    name: 'TaloWire',
    username: 'talowire',
    avatar: 'https://i.pravatar.cc/150?img=5',
    banner: 'https://picsum.photos/800/200?random=5',
    followers: 265000,
    isLive: true,
    isFollowing: true,
  },
  {
    id: 6,
    name: 'LiveWarrior',
    username: 'livewarrior',
    avatar: 'https://i.pravatar.cc/150?img=6',
    banner: 'https://picsum.photos/800/200?random=6',
    followers: 52000,
    isLive: true,
    isFollowing: false,
  },
  {
    id: 7,
    name: 'SceneRules',
    username: 'scenerules',
    avatar: 'https://i.pravatar.cc/150?img=7',
    banner: 'https://picsum.photos/800/200?random=7',
    followers: 28000,
    isLive: true,
    isFollowing: false,
  },
  {
    id: 8,
    name: 'Epicname',
    username: 'epicname',
    avatar: 'https://i.pravatar.cc/150?img=8',
    banner: 'https://picsum.photos/800/200?random=8',
    followers: 17500,
    isLive: false,
    isFollowing: true,
  },
  {
    id: 9,
    name: 'Sessiveed',
    username: 'sessiveed',
    avatar: 'https://i.pravatar.cc/150?img=9',
    banner: 'https://picsum.photos/800/200?random=9',
    followers: 9200,
    isLive: false,
    isFollowing: true,
  },
  {
    id: 10,
    name: 'Netcentral',
    username: 'netcentral',
    avatar: 'https://i.pravatar.cc/150?img=10',
    banner: 'https://picsum.photos/800/200?random=10',
    followers: 11800,
    isLive: false,
    isFollowing: true,
  },
  {
    id: 11,
    name: 'Maggerztt',
    username: 'maggerztt',
    avatar: 'https://i.pravatar.cc/150?img=11',
    banner: 'https://picsum.photos/800/200?random=11',
    followers: 5600,
    isLive: false,
    isFollowing: true,
  },
];

export const mockCategories: Category[] = [
  {
    id: 1,
    name: 'Overwatch 2',
    thumbnail: 'https://picsum.photos/200/280?random=101',
    viewerCount: 525000,
  },
  {
    id: 2,
    name: 'Dota 2',
    thumbnail: 'https://picsum.photos/200/280?random=102',
    viewerCount: 512000,
  },
  {
    id: 3,
    name: 'Valorant',
    thumbnail: 'https://picsum.photos/200/280?random=103',
    viewerCount: 108000,
  },
  {
    id: 4,
    name: 'Apex Legends',
    thumbnail: 'https://picsum.photos/200/280?random=104',
    viewerCount: 172000,
  },
  {
    id: 5,
    name: 'League of Legends',
    thumbnail: 'https://picsum.photos/200/280?random=105',
    viewerCount: 108000,
  },
  {
    id: 6,
    name: 'Genshin Impact',
    thumbnail: 'https://picsum.photos/200/280?random=106',
    viewerCount: 183000,
  },
  {
    id: 7,
    name: 'Valorant',
    thumbnail: 'https://picsum.photos/200/280?random=107',
    viewerCount: 182000,
  },
];

export const mockStreams: Stream[] = [
  {
    id: 1,
    title: 'Playing UP Storylines',
    thumbnail: 'https://picsum.photos/400/225?random=201',
    channel: mockChannels[0],
    viewers: 3700,
    isLive: true,
    category: mockCategories[0],
  },
  {
    id: 2,
    title: 'Finished VS Condi',
    thumbnail: 'https://picsum.photos/400/225?random=202',
    channel: mockChannels[1],
    viewers: 1500,
    isLive: false,
    category: mockCategories[1],
  },
  {
    id: 3,
    title: 'Subscribe VS Tracktion',
    thumbnail: 'https://picsum.photos/400/225?random=203',
    channel: mockChannels[2],
    viewers: 2100,
    isLive: false,
    category: mockCategories[2],
  },
  {
    id: 4,
    title: 'Ransom VS Takeo',
    thumbnail: 'https://picsum.photos/400/225?random=204',
    channel: mockChannels[3],
    viewers: 950,
    isLive: false,
    category: mockCategories[0],
  },
  {
    id: 5,
    title: 'Drops Enable Overwatch 2 Gameplay',
    thumbnail: 'https://picsum.photos/400/225?random=205',
    channel: mockChannels[4],
    viewers: 45600,
    isLive: true,
    category: mockCategories[0],
  },
  {
    id: 6,
    title: 'Drops Enabled - [24H] Shapers Apex #364',
    thumbnail: 'https://picsum.photos/400/225?random=206',
    channel: mockChannels[5],
    viewers: 12400,
    isLive: true,
    category: mockCategories[3],
  },
  {
    id: 7,
    title: 'Ramsom VS Takenote',
    thumbnail: 'https://picsum.photos/400/225?random=207',
    channel: mockChannels[6],
    viewers: 8700,
    isLive: false,
    category: mockCategories[1],
  },
  {
    id: 8,
    title: 'Contest Livefest VS Storyarcs',
    thumbnail: 'https://picsum.photos/400/225?random=208',
    channel: mockChannels[7],
    viewers: 4200,
    isLive: false,
    category: mockCategories[2],
  },
  {
    id: 9,
    title: 'RealXuan VS Vanum',
    thumbnail: 'https://picsum.photos/400/225?random=209',
    channel: mockChannels[8],
    viewers: 1800,
    isLive: false,
    category: mockCategories[0],
  },
  {
    id: 10,
    title: 'Conquest VS Tanabe',
    thumbnail: 'https://picsum.photos/400/225?random=210',
    channel: mockChannels[9],
    viewers: 3100,
    isLive: false,
    category: mockCategories[1],
  },
];
