import { Channel, Stream, Category, Cybermahalla } from '@/types';

export const mockChannels: Channel[] = [
  {
    id: 1,
    name: 'InAdventure',
    username: 'inadventure',
    avatar: 'https://i.pravatar.cc/150?img=1',
    banner: 'https://picsum.photos/800/200?random=1',
    followers: 15200,
    isLive: true,
    isFollowing: true,
  },
  {
    id: 2,
    name: 'Circlemart',
    username: 'circlemart',
    avatar: 'https://i.pravatar.cc/150?img=2',
    banner: 'https://picsum.photos/800/200?random=2',
    followers: 8400,
    isLive: false,
    isFollowing: true,
  },
  {
    id: 3,
    name: 'Ironargyr',
    username: 'ironargyr',
    avatar: 'https://i.pravatar.cc/150?img=3',
    banner: 'https://picsum.photos/800/200?random=3',
    followers: 12500,
    isLive: true,
    isFollowing: true,
  },
  {
    id: 4,
    name: 'Kanagav',
    username: 'kanagav',
    avatar: 'https://i.pravatar.cc/150?img=4',
    banner: 'https://picsum.photos/800/200?random=4',
    followers: 6700,
    isLive: false,
    isFollowing: true,
  },
  {
    id: 5,
    name: 'TaloWire',
    username: 'talowire',
    avatar: 'https://i.pravatar.cc/150?img=5',
    banner: 'https://picsum.photos/800/200?random=5',
    followers: 265000,
    isLive: true,
    isFollowing: true,
  },
  {
    id: 6,
    name: 'LiveWarrior',
    username: 'livewarrior',
    avatar: 'https://i.pravatar.cc/150?img=6',
    banner: 'https://picsum.photos/800/200?random=6',
    followers: 52000,
    isLive: true,
    isFollowing: false,
  },
  {
    id: 7,
    name: 'SceneRules',
    username: 'scenerules',
    avatar: 'https://i.pravatar.cc/150?img=7',
    banner: 'https://picsum.photos/800/200?random=7',
    followers: 28000,
    isLive: true,
    isFollowing: false,
  },
  {
    id: 8,
    name: 'Epicname',
    username: 'epicname',
    avatar: 'https://i.pravatar.cc/150?img=8',
    banner: 'https://picsum.photos/800/200?random=8',
    followers: 17500,
    isLive: false,
    isFollowing: true,
  },
  {
    id: 9,
    name: 'Sessiveed',
    username: 'sessiveed',
    avatar: 'https://i.pravatar.cc/150?img=9',
    banner: 'https://picsum.photos/800/200?random=9',
    followers: 9200,
    isLive: false,
    isFollowing: true,
  },
  {
    id: 10,
    name: 'Netcentral',
    username: 'netcentral',
    avatar: 'https://i.pravatar.cc/150?img=10',
    banner: 'https://picsum.photos/800/200?random=10',
    followers: 11800,
    isLive: false,
    isFollowing: true,
  },
  {
    id: 11,
    name: 'Maggerztt',
    username: 'maggerztt',
    avatar: 'https://i.pravatar.cc/150?img=11',
    banner: 'https://picsum.photos/800/200?random=11',
    followers: 5600,
    isLive: false,
    isFollowing: true,
  },
];

export const mockCategories: Category[] = [
  {
    id: 1,
    name: 'Overwatch 2',
    thumbnail: 'https://picsum.photos/200/280?random=101',
    viewerCount: 525000,
  },
  {
    id: 2,
    name: 'Dota 2',
    thumbnail: 'https://picsum.photos/200/280?random=102',
    viewerCount: 512000,
  },
  {
    id: 3,
    name: 'Valorant',
    thumbnail: 'https://picsum.photos/200/280?random=103',
    viewerCount: 108000,
  },
  {
    id: 4,
    name: 'Apex Legends',
    thumbnail: 'https://picsum.photos/200/280?random=104',
    viewerCount: 172000,
  },
  {
    id: 5,
    name: 'League of Legends',
    thumbnail: 'https://picsum.photos/200/280?random=105',
    viewerCount: 108000,
  },
  {
    id: 6,
    name: 'Genshin Impact',
    thumbnail: 'https://picsum.photos/200/280?random=106',
    viewerCount: 183000,
  },
  {
    id: 7,
    name: 'Valorant',
    thumbnail: 'https://picsum.photos/200/280?random=107',
    viewerCount: 182000,
  },
];

export const mockStreams: Stream[] = [
  {
    id: 1,
    title: 'Playing UP Storylines',
    thumbnail: 'https://picsum.photos/400/225?random=201',
    channel: mockChannels[0],
    viewers: 3700,
    isLive: true,
    category: mockCategories[0],
  },
  {
    id: 2,
    title: 'Finished VS Condi',
    thumbnail: 'https://picsum.photos/400/225?random=202',
    channel: mockChannels[1],
    viewers: 1500,
    isLive: false,
    category: mockCategories[1],
  },
  {
    id: 3,
    title: 'Subscribe VS Tracktion',
    thumbnail: 'https://picsum.photos/400/225?random=203',
    channel: mockChannels[2],
    viewers: 2100,
    isLive: false,
    category: mockCategories[2],
  },
  {
    id: 4,
    title: 'Ransom VS Takeo',
    thumbnail: 'https://picsum.photos/400/225?random=204',
    channel: mockChannels[3],
    viewers: 950,
    isLive: false,
    category: mockCategories[0],
  },
  {
    id: 5,
    title: 'Drops Enable Overwatch 2 Gameplay',
    thumbnail: 'https://picsum.photos/400/225?random=205',
    channel: mockChannels[4],
    viewers: 45600,
    isLive: true,
    category: mockCategories[0],
  },
  {
    id: 6,
    title: 'Drops Enabled - [24H] Shapers Apex #364',
    thumbnail: 'https://picsum.photos/400/225?random=206',
    channel: mockChannels[5],
    viewers: 12400,
    isLive: true,
    category: mockCategories[3],
  },
  {
    id: 7,
    title: 'Ramsom VS Takenote',
    thumbnail: 'https://picsum.photos/400/225?random=207',
    channel: mockChannels[6],
    viewers: 8700,
    isLive: false,
    category: mockCategories[1],
  },
  {
    id: 8,
    title: 'Contest Livefest VS Storyarcs',
    thumbnail: 'https://picsum.photos/400/225?random=208',
    channel: mockChannels[7],
    viewers: 4200,
    isLive: false,
    category: mockCategories[2],
  },
  {
    id: 9,
    title: 'RealXuan VS Vanum',
    thumbnail: 'https://picsum.photos/400/225?random=209',
    channel: mockChannels[8],
    viewers: 1800,
    isLive: false,
    category: mockCategories[0],
  },
  {
    id: 10,
    title: 'Conquest VS Tanabe',
    thumbnail: 'https://picsum.photos/400/225?random=210',
    channel: mockChannels[9],
    viewers: 3100,
    isLive: false,
    category: mockCategories[1],
  },
];

export const mockCybermahallas: Cybermahalla[] = [
  {
    id: 1,
    name: 'Chilanzar Gamers',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=chilanzar',
    banner: 'https://picsum.photos/800/200?random=301',
    description: 'Chilanzar tumani gamerlarining rasmiy jamoasi',
    members: 2500,
    isJoined: true,
    categories: ['CS:GO', 'Dota 2', 'Valorant'],
    activeCompetitions: 3,
    createdAt: '2023-01-15',
    isOnline: true,
  },
  {
    id: 2,
    name: 'Yunusabad Warriors',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=yunusabad',
    banner: 'https://picsum.photos/800/200?random=302',
    description: 'Yunusabad pro gamerlar jamiyati',
    members: 3200,
    isJoined: true,
    categories: ['Mobile Legends', 'PUBG', 'Free Fire'],
    activeCompetitions: 5,
    createdAt: '2022-11-20',
    isOnline: true,
  },
  {
    id: 3,
    name: 'Sergeli Esports',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=sergeli',
    banner: 'https://picsum.photos/800/200?random=303',
    description: 'Sergeli tumani esports club',
    members: 1800,
    isJoined: true,
    categories: ['League of Legends', 'Valorant'],
    activeCompetitions: 2,
    createdAt: '2023-03-10',
    isOnline: false,
  },
  {
    id: 4,
    name: 'Mirzo Ulugbek Squad',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=mirzoulugbek',
    banner: 'https://picsum.photos/800/200?random=304',
    description: 'MU gamerlar uyushmasi',
    members: 2100,
    isJoined: true,
    categories: ['Dota 2', 'CS:GO'],
    activeCompetitions: 4,
    createdAt: '2023-02-05',
    isOnline: true,
  },
  {
    id: 5,
    name: 'Yakkasaray Elite',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=yakkasaray',
    banner: 'https://picsum.photos/800/200?random=305',
    description: 'Yakkasaray tumani elite gamers',
    members: 1500,
    isJoined: true,
    categories: ['Apex Legends', 'Fortnite'],
    activeCompetitions: 1,
    createdAt: '2023-04-12',
    isOnline: false,
  },
  {
    id: 6,
    name: 'Shaykhontohur Legends',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=shaykhontohur',
    banner: 'https://picsum.photos/800/200?random=306',
    description: 'Shaykhontohur pro gamerlar',
    members: 1900,
    isJoined: true,
    categories: ['Mobile Legends', 'PUBG Mobile'],
    activeCompetitions: 2,
    createdAt: '2023-01-28',
    isOnline: true,
  },
  {
    id: 7,
    name: 'Yashnabad Titans',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=yashnabad',
    banner: 'https://picsum.photos/800/200?random=307',
    description: 'Yashnabad kuchli jamoasi',
    members: 2800,
    isJoined: false,
    categories: ['CS:GO', 'Valorant', 'Overwatch'],
    activeCompetitions: 6,
    createdAt: '2022-12-03',
    isOnline: true,
  },
  {
    id: 8,
    name: 'Bektemir Champions',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=bektemir',
    banner: 'https://picsum.photos/800/200?random=308',
    description: 'Bektemir tumani championlari',
    members: 1200,
    isJoined: false,
    categories: ['FIFA', 'NBA 2K'],
    activeCompetitions: 1,
    createdAt: '2023-05-20',
    isOnline: false,
  },
];
